### ISSUE TITLE
Override Problem Showed Up in VSCode But No Problem Compiling

### ISSUE THREAD

**Issue by fahadh4ilyas** [juanfranblanco/vscode-solidity#327]
I have a smart contract like this
```js
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "@openzeppelin/contracts/access/AccessControlEnumerable.sol";
import "@openzeppelin/contracts/utils/Context.sol";
import "@openzeppelin/contracts/security/Pausable.sol";

contract SampleContract is Context, AccessControlEnumerable, Pausable {
    grantRole(
        bytes32 role, 
        address account
    )
        public
        virtual
        override
    {
        super.grantRole(role, account);
        // do stuff after grantRole
    }
}
```

Somehow, this raise error in VS Code
```
Function needs to specify overridden contracts "AccessControl" and "IAccessControl".
```

But, when I tried to compiled it using `solc 0.8.11`, nothing happened. The compiler run successfully. I want to get rid of the error by adding `override(AccessControl, IAccessControl)`, but the compiler raised error like this
```
TypeError: Invalid contract specified in override list: "AccessControl".
  --> project:/contracts/SampleContract.sol:15:9:
   |
15 |         override(AccessControl, IAccessControl)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: This contract:
  --> @openzeppelin/contracts/access/AccessControl.sol:49:1:
   |
49 | abstract contract AccessControl is Context, IAccessControl, ERC165 {
   | ^ (Relevant source part starts here and spans across multiple lines).

Compilation failed. See above.
```

I don't understand why is this happening? How to solve this? At least I want to ignore error from VS Code because it's kind of misleading.

**Comment by cameel** [comment]
I think your code snippet is not the one that triggers the error message you're showing. You're missing the `function` keyword and also you have `override` there but the message clearly shows that you had `override(AccessControl, IAccessControl)` there when the code was being compiled.

In any case, adding `function` and `override(AccessControl, IAccessControl)` is everything you need for it to compile with 0.8.13. There used to be a bug, which resulted in `override` not always being required as it should have been (https://github.com/ethereum/solidity/issues/12615). It was fixed in 0.8.12. Unfortunately the result of fixing it is that some contracts that would compile without `override` before, no longer will. The changes needed to avoid this error are pretty straightforward though.

By the way, this has nothing to do with vscode-solidity specifically. It was a change in the compiler.

**Comment by fahadh4ilyas** [comment]
> I think your code snippet is not the one that triggers the error message you're showing. You're missing the `function` keyword and also you have `override` there but the message clearly shows that you had `override(AccessControl, IAccessControl)` there when the code was being compiled.
> 
> In any case, adding `function` and `override(AccessControl, IAccessControl)` is everything you need for it to compile with 0.8.13. There used to be a bug, which resulted in `override` not always being required as it should have been ([ethereum/solidity#12615](https://github.com/ethereum/solidity/issues/12615)). It was fixed in 0.8.12. Unfortunately the result of fixing it is that some contracts that would compile without `override` before, no longer will. The changes needed to avoid this error are pretty straightforward though.
> 
> By the way, this has nothing to do with vscode-solidity specifically. It was a change in the compiler.

Sorry, I forget to add `function` keyword in my question. But, I assure you that I already add `function` in my script. The problem  is from the `override(AccessControl, IAccessControl)`. Because if the reason of error is because `function` keyword, the compiler will select `function` keyword error first right?

**Comment by fahadh4ilyas** [comment]
@cameel Here is my proof

Here is how `vscode-solidity` telling me that writing `override` only is wrong...

![vscode-solidity telling me error](https://user-images.githubusercontent.com/37577369/165351208-2f552645-dd8c-4abb-a373-d1c7f1930da9.png)

Here is when I tried to compiled it...

![compiled successfully](https://user-images.githubusercontent.com/37577369/165351527-43262e98-6ad5-4e27-93ff-cfff85c9576f.png)

Here is when I tried to compiled it by adding `override(AccessControl, IAccessControl)`

![compile error](https://user-images.githubusercontent.com/37577369/165351892-a7d83a96-6031-40a1-a3d5-44430dc872ae.png)

**Comment by fahadh4ilyas** [comment]
> It's not that I don't believe you, I just don't know all the factors coming into play here and a broken snippet did not help :)
> 
> First of all, if vscode-solidity and Truffle each compile one version but not the other, it's almost certain that they're using different compiler versions under the hood. Like I said, this did change in the compiler between 0.8.11 and 0.8.12 so the error is real, the problem is just why it's so inconsistent for you. Can you verify which compiler are you using with vscode-solidity? I'm pretty sure it's 0.8.12 or later.

Where can I see compiler version of `vscode-solidity`? Because I'm using solc 0.8.11 in my truffle.

> Also, the error you get from Truffle on the second screenshot seems truncated or mangled. Does it always look like this for you? It should contain the error message that vscode-solidity is showing you in the first screenshot. You might want to report this as a problem in Truffle if it's reproducible (I mean just the way the error is shown, not the fact that there is an error as that's expected).

That's not make sense, because from my second screenshot, it literally show that contracts are compiled successfully even though `vscode-solidity` said otherwise. The compiler is like the opposite of `vscode-solidity`. Compiler said that writing `override` only is right. But `vscode-solidity` said that writing `override(AccessControl, IAccessControl)` is right. So the last screenshot showing that the error is because of writing `override(AccessControl, IAccessControl)`. Here is the verbose version of the error.

![verbose of error](https://user-images.githubusercontent.com/37577369/165357292-877e8a3f-85b8-4782-b499-4b129e7163fd.png)

**Comment by cameel** [comment]
> Where can I see compiler version of `vscode-solidity`? Because I'm using solc 0.8.11 in my truffle.

[README](https://github.com/juanfranblanco/vscode-solidity/blob/master/README.md) has some instructions on downloading selecting specific compiler versions. See if you can check it that way.

But if you want to be 100% sure you're using 0.8.11, just set the pragma to `pragma solidity 0.8.11`. It just won't compile with any other version then and you'll see the version that was actually used in the error message.

> That's not make sense, because from my second screenshot, it literally show that contracts are compiled successfully even though `vscode-solidity` said otherwise.

But it's not vscode-solidity running `yarn truffle compile` in your screenshot, is it? I'm assuming it's the command you ran manually and it can just as well be using a different compiler binary. Truffle and vscode-solidity manage compiler binaries independently as far as I know.

In any case, I'm not using vscode-solidity myself so I can be wrong about how it works but but I know the compiler I can tell you that this behavior is consistent with what you'd see if one was using 0.8.11 and the other 0.8.12.

> Here is the verbose version of the error.

Oh, so it was some kind of shortened output before? Right. Explains why it seemed mangled. Not a bug then :)
